import {
  Accessibility,
  Activity,
  AlertTriangle,
  Apple,
  Baby,
  Banknote,
  Bell,
  BookOpen,
  Building2,
  ClipboardList,
  CloudLightning,
  CloudRain,
  CloudSun,
  Coins,
  Cross,
  Droplets,
  FileText,
  Flame,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hospital,
  Landmark,
  Leaf,
  LifeBuoy,
  Lock,
  MapPin,
  Megaphone,
  Newspaper,
  Package,
  Phone,
  Pill,
  Plane,
  Radio,
  Route,
  Scale,
  School,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Siren,
  Snowflake,
  Sparkles,
  Stethoscope,
  Sun,
  Syringe,
  Tent,
  ThermometerSun,
  TrendingUp,
  Truck,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Waves,
  Wheat,
  Wind,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export type InterestIconKey = string;

export const INTEREST_ICON_OPTIONS: { key: InterestIconKey; label: string; Icon: LucideIcon }[] = [
  { key: 'utensils', label: 'Utensils', Icon: Utensils },
  { key: 'wheat', label: 'Wheat', Icon: Wheat },
  { key: 'apple', label: 'Apple', Icon: Apple },
  { key: 'users', label: 'Users', Icon: Users },
  { key: 'tent', label: 'Tent', Icon: Tent },
  { key: 'home', label: 'Home', Icon: Home },
  { key: 'baby', label: 'Baby', Icon: Baby },
  { key: 'heartHandshake', label: 'Heart handshake', Icon: HeartHandshake },
  { key: 'heart', label: 'Heart', Icon: Heart },
  { key: 'accessibility', label: 'Accessibility', Icon: Accessibility },
  { key: 'cloudRain', label: 'Cloud rain', Icon: CloudRain },
  { key: 'cloudSun', label: 'Cloud sun', Icon: CloudSun },
  { key: 'cloudLightning', label: 'Cloud lightning', Icon: CloudLightning },
  { key: 'sun', label: 'Sun', Icon: Sun },
  { key: 'snowflake', label: 'Snowflake', Icon: Snowflake },
  { key: 'wind', label: 'Wind', Icon: Wind },
  { key: 'waves', label: 'Waves', Icon: Waves },
  { key: 'thermometerSun', label: 'Thermometer', Icon: ThermometerSun },
  { key: 'flame', label: 'Flame', Icon: Flame },
  { key: 'umbrella', label: 'Umbrella', Icon: Umbrella },
  { key: 'leaf', label: 'Leaf', Icon: Leaf },
  { key: 'droplets', label: 'Droplets', Icon: Droplets },
  { key: 'hospital', label: 'Hospital', Icon: Hospital },
  { key: 'cross', label: 'Cross', Icon: Cross },
  { key: 'syringe', label: 'Syringe', Icon: Syringe },
  { key: 'stethoscope', label: 'Stethoscope', Icon: Stethoscope },
  { key: 'pill', label: 'Pill', Icon: Pill },
  { key: 'heartPulse', label: 'Heart pulse', Icon: HeartPulse },
  { key: 'shieldAlert', label: 'Shield alert', Icon: ShieldAlert },
  { key: 'shield', label: 'Shield', Icon: Shield },
  { key: 'shieldCheck', label: 'Shield check', Icon: ShieldCheck },
  { key: 'alertTriangle', label: 'Alert triangle', Icon: AlertTriangle },
  { key: 'siren', label: 'Siren', Icon: Siren },
  { key: 'lifeBuoy', label: 'Life buoy', Icon: LifeBuoy },
  { key: 'lock', label: 'Lock', Icon: Lock },
  { key: 'wallet', label: 'Wallet', Icon: Wallet },
  { key: 'coins', label: 'Coins', Icon: Coins },
  { key: 'banknote', label: 'Banknote', Icon: Banknote },
  { key: 'handCoins', label: 'Hand coins', Icon: HandCoins },
  { key: 'package', label: 'Package', Icon: Package },
  { key: 'truck', label: 'Truck', Icon: Truck },
  { key: 'ship', label: 'Ship', Icon: Ship },
  { key: 'plane', label: 'Plane', Icon: Plane },
  { key: 'route', label: 'Route', Icon: Route },
  { key: 'mapPin', label: 'Map pin', Icon: MapPin },
  { key: 'globe', label: 'Globe', Icon: Globe },
  { key: 'building2', label: 'Buildings', Icon: Building2 },
  { key: 'landmark', label: 'Landmark', Icon: Landmark },
  { key: 'school', label: 'School', Icon: School },
  { key: 'graduationCap', label: 'Graduation cap', Icon: GraduationCap },
  { key: 'handshake', label: 'Handshake', Icon: Handshake },
  { key: 'scale', label: 'Scale', Icon: Scale },
  { key: 'fileText', label: 'File', Icon: FileText },
  { key: 'clipboardList', label: 'Clipboard list', Icon: ClipboardList },
  { key: 'newspaper', label: 'Newspaper', Icon: Newspaper },
  { key: 'bookOpen', label: 'Open book', Icon: BookOpen },
  { key: 'trendingUp', label: 'Trending up', Icon: TrendingUp },
  { key: 'activity', label: 'Activity', Icon: Activity },
  { key: 'sparkles', label: 'Sparkles', Icon: Sparkles },
  { key: 'bell', label: 'Bell', Icon: Bell },
  { key: 'megaphone', label: 'Megaphone', Icon: Megaphone },
  { key: 'radio', label: 'Radio', Icon: Radio },
  { key: 'phone', label: 'Phone', Icon: Phone },
  { key: 'wrench', label: 'Wrench', Icon: Wrench },
];

const LEGACY_ICON_ALIASES: Record<string, InterestIconKey> = {
  food: 'utensils',
  displacement: 'users',
  climate: 'cloudRain',
  funding: 'wallet',
  security: 'shieldAlert',
  wash: 'droplets',
  gender: 'heartHandshake',
  earlyWarning: 'sparkles',
};

const ICON_BY_KEY = new Map(INTEREST_ICON_OPTIONS.map((opt) => [opt.key, opt]));

export function resolveInterestIconKey(key: string | undefined): InterestIconKey {
  if (!key) return 'sparkles';
  if (ICON_BY_KEY.has(key)) return key;
  return LEGACY_ICON_ALIASES[key] ?? 'sparkles';
}

export function getInterestIcon(key: string | undefined): LucideIcon {
  return ICON_BY_KEY.get(resolveInterestIconKey(key))?.Icon ?? Sparkles;
}

export function getInterestIconLabel(key: string | undefined): string {
  return ICON_BY_KEY.get(resolveInterestIconKey(key))?.label ?? 'Sparkles';
}

/** @deprecated Use getInterestIcon — kept for existing call sites. */
export const INTEREST_ICONS: Record<string, LucideIcon> = Object.fromEntries(
  INTEREST_ICON_OPTIONS.map((opt) => [opt.key, opt.Icon]),
);
